name: platform-pipeline
on:
  pull_request:
    branches:
      - 'main'
jobs:
  release:
    runs-on: nexient-llc/platform-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run Make Check
        uses: ./.github/actions/check
      - name: Run Pre-merge
        uses: ./.github/actions/pre-merge
      - name: Run Make Release
        run: |
          make release
