name: platform-check
on: [push, workflow_call]
jobs:
  check:
    runs-on: nexient-llc/platform-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run Make Check
        uses: ./.github/actions/check
