name: pipeline-check
on:
  pull_request:
    branches:
      - 'main'
jobs:
  check:
    runs-on: ubuntu-latest
    uses: nexient-llc/.github/workflows/platform-release.yml@0282568081885110f0d358de443c3870d5e91879
