name: pipeline-release
on:
  pull_request:
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: nexientdevops/platform-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: fix github known_hosts issues
        run: mkdir -m 0700 -p ~/.ssh && ssh-keyscan github.com | tee -a ~/.ssh/known_hosts
      - uses: ./.github/actions/configure
        with:
          JOB_NAME: "job"
          JOB_EMAIL: "job@job.job"
      - uses: ./.github/actions/check
      - uses: ./.github/actions/release
